import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";

import { cn } from "@/lib/utils";

const vazirFont = localFont({
  src: [
    {
      path: "../public/fonts/Vazirmatn-ExtraBold.woff2",
      weight: "800",
    },
    {
      path: "../public/fonts/Vazirmatn-Bold.woff2",
      weight: "700",
    },
    {
      path: "../public/fonts/Vazirmatn-SemiBold.woff2",
      weight: "600",
    },
    {
      path: "../public/fonts/Vazirmatn-Medium.woff2",
      weight: "500",
    },
    {
      path: "../public/fonts/Vazirmatn-Regular.woff2",
      weight: "400",
    },
    {
      path: "../public/fonts/Vazirmatn-Light.woff2",
      weight: "300",
    },
    {
      path: "../public/fonts/Vazirmatn-ExtraLight.woff2",
      weight: "900",
    },
    {
      path: "../public/fonts/Vazirmatn-Thin.woff2",
      weight: "100",
    },
  ],

  variable: "--vazir-font",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="fa" dir="rtl">
      <body className={cn("min-h-screen vazir-font px-5", vazirFont.className)}>
        {children}
      </body>
    </html>
  );
}
